Repository JuliaData/MemPool.jl, pull requests merged in 2024-04, with the labels that each got.

#79 datastore: Amortize RefCounters allocation
  Project.toml
  src/MemPool.jl
  src/datastore.jl
  src/storage.jl
Labels: enhancement, performance, memory usage

#80 Add DRef migration support
  .github/workflows/test.yml
  Project.toml
  src/datastore.jl
  src/storage.jl
  test/runtests.jl
Labels: enhancement, needs docs, needs tests, mobility

#83 Add a type assertion to remove some invalidations
  src/storage.jl
Labels: latency

#85 Vendor ReadWriteLock from ConcurrentUtils
  Project.toml
  src/MemPool.jl
  src/datastore.jl
  src/read_write_lock.jl
  src/storage.jl
Labels: bug
